"""
Student information for this assignment:

Replace <FULL NAME> with your name.
On my/our honor, Anthony Dezdha and <FULL NAME>, this
programming assignment is my own work and I have not provided this code to
any other student.

I have read and understand the course syllabus's guidelines regarding Academic
Integrity. I understand that if I violate the Academic Integrity policy (e.g.
copy code from someone else, have the code generated by an LLM, or give my
code to someone else), the case shall be submitted to the Office of the Dean of
Students. Academic penalties up to and including an F in the course are likely.

UT EID 1:AD54489
UT EID 2:
"""

from abc import ABC, abstractmethod
import random

DAILY_EXPENSE = 60
HAPPINESS_THRESHOLD = 50
MANAGER_BONUS = 1000
TEMP_EMPLOYEE_PERFORMANCE_THRESHOLD = 50
PERM_EMPLOYEE_PERFORMANCE_THRESHOLD = 25
RELATIONSHIP_THRESHOLD = 10
INITIAL_PERFORMANCE = 75
INITIAL_HAPPINESS = 50
PERCENTAGE_MAX = 100
PERCENTAGE_MIN = 0
SALARY_ERROR_MESSAGE = "Salary must be non-negative."


# TODO: implement this class. You may delete this comment when you are done.
class Employee(ABC):
    """
    Abstract base class representing a generic employee in the system.
    """
#ensure setup has every sublcas, same basicsetup
#name, manager read only, salary is setter and property due to possibility of neg
"""name (string, read-only): The name of the employee. This is a private instance variable that can only be accessed via a public property. It is read-only.
manager (None or Manager, read-only): The employee's manager. This is a private instance variable that can only be accessed via a public property. It is read-only.
performance (integer): The employee’s performance on a percentage scale of 0 to 100 as an integer value (PERCENTAGE_MIN to PERCENTAGE_MAX). The value is automatically clamped between 0 and 100 if a value that is out of range is given.
happiness (integer): The employee’s happiness on a percentage scale of 0 to 100 as an integer value (PERCENTAGE_MIN to PERCENTAGE_MAX). The value is automatically clamped between 0 and 100 if a value that is out of range is given.
salary (integer): The employee’s salary. Salaries must always be non-negative, and attempting to set a negative value raises a ValueError with the corresponding message SALARY_ERROR_MESSAGE.
"""
    def __init__(self, name, manager, salary, savings):
        self.relationships = {}
        self.savings = savings
        self.is_employed = True

        self.__name = name #priv
        self.__manager = manager #priv

        self.performance = INITIAL_PERFORMANCE
        self.happiness = INITIAL_HAPPINESS
        self.salary = salary #prop non neg
        #set our properties, spec for salary requiring both
    @property
    def name(self):
        return self.__name
    @property
    def manager(self):
        return self.__manager
    @property
    def salary(self):
        return self.__salary
    @salary.setter
    def salary(self, value):
        if value < 0:
            raise ValueError(SALARY_ERROR_MESSAGE)
        self.__salary = value
    def daily_expense(self):
        #decrease happy by 1 and reduce our savings by the amount in daily
        # if savings fall below 0, employee is nO LONGER EMPLOYED!
        self.happiness -= 1
        self.savings -= DAILY_EXPENSE
        if self.savings < 0:
            self.is_employed = False
    @abstractmethod
    def work(self):
        pass
    def interact(self, employee):
        #check our interaction dic, if yes do as by  start 1 and if not do as start by 1
        if employee.name in self.relationships:
            self.relationships[employee.name] += 1
        else:
            self.relationships[employee.name] = 1
    def __str__(self):
        return (
            f"{self.name}\n"
            f"\tSalary: ${self.salary}\n"
            f"\tSavings: ${self.savings}\n"
            f"\tHappiness: {self.happiness}%\n"
            f"\tPerformance: {self.performance}%"
        )

# TODO: implement this class. You may delete this comment when you are done.
class Manager(Employee):
    """
    A subclass of Employee representing a manager.
    """
    def work(self):
        #-5, 5 randint adjust randomly
        #if perf is less than 0, set to 0
        # if + add one to mans happy
        perfchange = random.randint(-5, 5)
        self.performance += perfchange
        self.performance = max(0, min(100, self.performance))

        if perfchange <= 0:
            self.happiness -= 1
            for x in self.relationships:
                self.relationships[x] -= 1
        else:
            self.happiness += 1
        self.happiness = max(0, min(100, self.happiness))


# TODO: implement this class. You may delete this comment when you are done.
class TemporaryEmployee(Employee):
    """
    A subclass of Employee representing a temporary employee.
    """


# TODO: implement this class. You may delete this comment when you are done.
class PermanentEmployee(Employee):
    """
    A subclass of Employee representing a permanent employee.
    """
    # -10, 10 randint
    #non neg then emp happy + 1
    #if perf (-) happy -1
    def work(self):
        perfchange = random.randint(-10, 10)
        self.performance += perfchange
        self.performance = max(0, min(100, self.performance))
        if perfchange >= 0:
            self.happiness += 1
        else:
            self.happiness -= 1
        self.happiness = max(0, min(100, self.happiness))
    def interact(self,employee):
        super().interact(employee)
        if employee.happiness > HAPPINESS_THRESHOLD \
            and self.performance > PERM_EMPLOYEE_PERFORMANCE_THRESHOLD:
                self.savings += MANAGER_BONUS
        elif employee.happiness <= HAPPINESS_THRESHOLD:
            self.happiness -= 1
